echo "Prefix Key:               <C-b>"
echo "--> Panes:"
echo "Split vertically:         %"
echo "Split horizontally:       \""
echo "Change pane:              <Arrow-Keys>"
echo "Close pane:               'exit' or <C-d>"
echo "--> Windows:"
echo "New window:               c"
echo "Goto previous window:     p"
echo "Goto next window:         n"
echo "Goto window:              <number>"
echo "--> Sessions:"
echo "Detach current session:   d"
echo "Attach to session:        \`tmux attach -t <name>\`"
echo "List sessions:            \`tmux ls\`"
echo "Create session:           \`tmux new -s <name>\`"
echo "Rename session:           \`tmux rename-session -t <old-name> <new-name>\`"

